<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function ($page) use ($urlPattern) {
            if (!preg_match('/page/', $urlPattern))
                return $urlPattern . "/page/" . $page;
            else
                return preg_replace('/\d/', $page, $urlPattern);
        };
?>
<center>
<?php if ($this->pageCount): ?>
        <div class="paginationControl">
        <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> de <?php echo $this->totalItemCount; ?> páginas
            <br />

<ul class="pager">
            <!-- First page link -->
    <?php if (isset($this->previous)): ?>
               <li> <a href="<?php echo $formatUrl($this->previous) ?>">
                    Primeira
                </a>  </li>
    <?php else: ?>
                
                <li><span class="disabled">Primeira</span></li> 
            <?php endif; ?>


            <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
               <li> <a href="<?php echo $formatUrl($this->previous) ?>">
                    < Anterior
                </a></li> 
    <?php else: ?>
               <li> <span class="disabled">< Anterior</span> 
            <?php endif; ?></li>


            <!-- Next page link -->
    <?php if (isset($this->next)): ?>
              <li>  <a href="<?php echo $formatUrl($this->next); ?>">
                    Próximo >
                </a> </li>
    <?php else: ?>
               <li> <span class="disabled">Próximo ></span> </li>
            <?php endif; ?>


            <!-- Last page link -->
    <?php if (isset($this->next)): ?>
              <li>  <a href="<?php echo $formatUrl($this->next); ?>">
                    Último
                </a></li>
    <?php else: ?>
             <li>   <span class="disabled">Último</span>
            <?php endif; ?></li>

        </div>
        </ul>

<?php endif; ?>
</center>