<h3>Nova Carta</h3>
<br/>

<?php 
$form = $this->form;

$form->setAttribute('action', $this->url('livraria-admin', array('controller'=>'cartas', 'action'=>'new')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('cidade'));
echo $this->formRow($form->get('cpf'));
echo $this->formRow($form->get('data'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>